### PR TITLE
Label based on branch name. Start w/fix+features

### PR DESCRIPTION
**Pull request by qcasey**
I like how the secretary automatically applies labels. This PR extends that feature to apply the labels `bug` and `enhancement` to `fix*` and `feature*` branches, respectively. As per my comment [here](https://github.com/paperless-ngx/paperless-ngx/pull/1301#issuecomment-1207441834) it should help correctly categorize PRs for our changelogs

### RFC

I have not tested this at all. @bauerj when you get a chance, could you please look this over for correctness? :)

### CODE REVIEW

**Comment by tooomm** [comment]
The release-drafter action should also be capable of this and is perhaps easier to set up and configure? See https://github.com/release-drafter/release-drafter#autolabeler. We could add it to [project-actions.yml](https://github.com/paperless-ngx/paperless-ngx/blob/main/.github/workflows/project-actions.yml), what do you think?

**Comment by qcasey** [comment]
[I did try that](https://github.com/paperless-ngx/paperless-ngx/commit/92f536cad88a0d10c9f733ed548f654353b59da9), funny enough I thought the opposite and went with consolidating all our labels to the secretary app. 

I don't care all that much, although I agree a .yml is easier to configure. I'll test autolabeler on my fork for completeness and we could just use that.

**Comment by qcasey** [comment]
autolabeler works just as well, and also labels based on PR titles. Let's use that instead. Thanks @tooomm

**Comment by bauerj** [comment]
Sorry for my late reply but I'm happy you found a better solution 🙂

**Pull request closed without merging**
